library(grid)
library(fitdistrplus)
library(Rmisc)
library(broom)
library(formattable)
library(kableExtra)
library(knitr)
library(shinydashboard)
library(DBI)
library(RSQLite)
library(DT)
library(shinyjs)
library(shinycssloaders)
library(lubridate)
library(scales)
library(ggplot2)
library(GGally)
library(tidyr)
library(dplyr)
library(readr)
library(tibble)
library(stringr)
library(purrr)
library(forcats)
library(plotly)
library(setGplot)
library(setPlotly)
library(ProcessCapability)
library(spcChart)
library(qcc)
library(outliers)
library(car)
library(pwr)

addResourcePath("www", file.path("..", "www_eles"))
theme_set(theme_bw())
tz <- "Asia/Taipei"
Sys.setenv(TZ = tz)

source(file.path("rCode", "functions.R"))
source(file.path("..", "www_eles", "ui_helpers.R"))

